### ISSUE TITLE
yarn build fails: error TS7016: Could not find a declaration file for module 'web-streams-polyfill/dist/ponyfill.es2018.js'

### ISSUE THREAD

**Issue by michaelkirk** [flatgeobuf/flatgeobuf#132]
`yarn build` succeeds for me as of 899ca24 , but fails after that (starting with 0f807f3751531e4cb55ec66053258da414474be9, and including current master - 0f807f3).

```
$ yarn build
yarn run v1.22.10
$ tsc -p config/tsconfig.mjs.json && tsc -p config/tsconfig.cjs.json && rollup -c config/rollup.config.js
src/ts/streams/utils.ts:1:32 - error TS7016: Could not find a declaration file for module 'web-streams-polyfill/dist/ponyfill.es2018.js'. '/Users/mkirk/src/georust/flatgeobuf-master/node_modules/web-streams-polyfill/dist/ponyfill.es2018.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/web-streams-polyfill` if it exists or add a new declaration (.d.ts) file containing `declare module 'web-streams-polyfill/dist/ponyfill.es2018.js';`

1 import { ReadableStream } from 'web-streams-polyfill/dist/ponyfill.es2018.js'
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bjornharrtell** [comment]
Mm it has to do with me trying to get rid of "edm" dep and trying to use native module support in node. Need to work on it some more..
